os: linux
dist: bionic
language: python
python: 3.8

branches:
  only:
    # Build tags and branches named master or starting with
    # 'v' followed by a digit, such as for version tags.
    - master
    - /^v\d.*$/

services:
  - docker

env:
  global:
    - IMAGE_NAME=hydra

jobs:
  include:
    - stage: Build
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - travis_wait 60 docker build --pull --no-cache -t $IMAGE_NAME .
      - docker run --rm -it $IMAGE_NAME pyenv versions
      - docker tag $IMAGE_NAME $DOCKER_USERNAME/$IMAGE_NAME
      - docker push $DOCKER_USERNAME/$IMAGE_NAME
