name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        pythons:
#          - (2.7 3.{5,6,7,8} pypy{2.7-7.{0,1,2,3},3.6-7.{0,1,2,3}})
#          - (3.{6,7,8} pypy3.6-7.3)
          - (3.8 pypy3.6-7.3)
        config:
          - os: ubuntu-18.04
            base: ubuntu:19.10
            platform: ubuntu
#          - os: windows-2019
#            base: ? https://hub.docker.com/_/microsoft-windows
#            platform: windows
#          - os: macos-10.15
#            base: ?
#            platform: macos
    env:
      IMAGE_NAME: hydra_testing-${{ matrix.config.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          docker build --pull --no-cache --tag "${IMAGE_NAME}:latest" --build-arg FROM='${{ matrix.config.base }}' --build-arg PYTHONS="${{ matrix.pythons }}" --file 'Dockerfile.${{ matrix.config.platform }}' .
          docker tag "${IMAGE_NAME}:latest" "${DOCKER_USERNAME}/${IMAGE_NAME}"
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
      - name: Report
        run: |
          docker run --rm "${IMAGE_NAME}:latest" pyenv versions
          docker run --rm "${IMAGE_NAME}:latest" pip --version
          docker run --rm "${IMAGE_NAME}:latest" pip freeze --all
      - name: Upload
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker push "${DOCKER_USERNAME}/${IMAGE_NAME}"
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
      - name: Use Image
        uses: docker://altendky/hydra:latest
      - name: Test
        run: |
          pyenv versions
          pip --version
          pip freeze --all
