name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        pythons:
          - name: 2-3-minors
            versions: (2.7 3.{5,6,7,8} pypy{2,3})
          - name: 2-3-latest
            versions: (2 3 pypy{2,3})
          - name: 3-minors
            versions: (3.{5,6,7,8} pypy3)
          - name: 3-latest
            versions: (3 pypy3)
        config:
          - os: ubuntu-18.04
            base: ubuntu:19.10
            platform: ubuntu
#          - os: windows-2019
#            base: ? https://hub.docker.com/_/microsoft-windows
#            platform: windows
#          - os: macos-10.15
#            base: ?
#            platform: macos
    env:
      IMAGE_NAME: hydra_testing
      IMAGE_TAG: ${IMAGE_NAME}:${{ matrix.config.platform }}-${{ matrix.pythons.name }}
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          docker build --pull --no-cache --tag "${IMAGE_TAG}" --build-arg FROM='${{ matrix.config.base }}' --build-arg PYTHONS="${{ matrix.pythons.versions }}" --file 'Dockerfile.${{ matrix.config.platform }}' .
          docker tag "${IMAGE_TAG}" "${DOCKER_USERNAME}/${IMAGE_NAME}"
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
      - name: Report
        run: |
          docker run --rm "${IMAGE_TAG}" pyenv versions
          docker run --rm "${IMAGE_TAG}" pip --version
          docker run --rm "${IMAGE_TAG}" pip freeze --all
      - name: Upload
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker push "${DOCKER_USERNAME}/${IMAGE_TAG}"
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
      - name: Use Image
        uses: docker://altendky/${IMAGE_TAG}
      - name: Test
        run: |
          pyenv versions
          pip --version
          pip freeze --all
